---
title: "Pew Cleaning"
author: "Jake Chanenson"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(foreign)      
library(ggplot2)      
library(colorspace)   #better colors for ggplot
library(tidyverse)    
library(dplyr)
library(gridExtra)
library(viridis)
library(ggridges)
library(socviz)
library(broom)
library(stargazer)
library(corrr)
library(GGally)
library(haven) #needed to import stada data
saveVal <- F #flag to see if the .Rda fale has been saved this session
```


## Initial Data Import
```{r, include=FALSE}
if(!file.exists("../../Pew/pewTech.RData") ) { #skip import if RData file exists
# Data set from Pew 
importedData <- read_sav("../../Pew/ATP W49.sav")

# Add the QKEY col
pew <- importedData$QKEY

# Iterate through data set
for(i in 2:(ncol(importedData)-1)){ #skip the QKEY column (1st col) and the WEIGHT_W49 col (last col)
        temp <- as_factor(importedData[ , i])
        pew <- cbind(pew,temp)
        temp <- 0
}

# Add the WEIGHT_W49 col
temp <- as_factor(importedData[ , ncol(importedData)])
pew <- cbind(pew,temp)

# Show pew
head(pew)

# Save the file 
saveVal <- F
write.csv(pew, "../../Pew/Pew_Tech.csv")
save(pew, file = "../../Pew/pewTech.RData")
}
```

```{r load data}
load("../../Pew/pewTech.RData")
```


## Additions for KNOW Dummy Var
```{r}
###Generate KNOW Dummy Var###
count_df <- pew %>% mutate(K1T = ifelse(KNOW1_W49 == "Can track your visits and activity on the site", yes = 1, no = 0 ),
               K3T = ifelse(KNOW3_W49 == "Has created a contract between itself and its users about how it will use their data", yes = 1, no = 0),
               K4T = ifelse(KNOW4_W49 == "Information entered into the site is encrypted", yes = 1, no = 0),
               K7T = ifelse(KNOW7_W49 == "Internet service providers should treat all traffic on their networks equally", yes = 1, no = 0),
               K8T = ifelse(KNOW8_W49 == "A coworker who uses the same computer", yes = 1, no = 0),
               K9T = ifelse(KNOW9_W49 == "Picture of 2-step code", yes = 1, no = 0)
               ) %>% select(K1T, K3T, K4T, K7T, K8T, K9T)
# count_df

## Sum count dummies, add to pew data set
pew <- pew %>% mutate(sumKnow134789 = count_df$K1T+count_df$K3T+count_df$K4T+count_df$K7T+count_df$K8T+count_df$K9T,
               propKnow134789 = sumKnow134789/6,
               .after = TOTALKNOW_W49)


###sumKnowFactor###
tmpfct <- as_factor(pew$sumKnow134789)
pew <- pew %>% mutate(sumKnowFactor = tmpfct, .after = sumKnow134789)

###groupKnow###
pew <- pew %>% mutate(groupKnow = ifelse(sumKnowFactor == 0, yes = "No Literacy",
                                   ifelse(sumKnowFactor == 1| sumKnowFactor == 2| sumKnowFactor == 3| sumKnowFactor == 4, yes = "Some Literacy", no = "High Literacy")),
               groupKnow = as_factor(groupKnow),
               .after = sumKnowFactor)
```



## Additions for RTBFG Dummy Var
```{r}
# TODO
```


```{r save updated data frame}
if(!file.exists("../../Pew/pewTech.RData") ) { #dummy proofing 
saveVal <- T
# Save the file 
save(pew, file = "../../Pew/pewTech.RData")
}
```



